spring:
  application:
    name: SECURITY-SERVICE
  datasource:
    url: jdbc:mysql://himanshu-rdbms.cb8keo4q4lbo.us-east-1.rds.amazonaws.com:3306/citizenDB
    password: Himanshu123
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/



server:
  port: 9890
