server:
  port: 8083
  
spring:
  application:
    name: API_GATEWAY
    
    
  cloud:
    gateway:
      routes:
      - id: CITIZEN-SERVICE
        uri:
          lb://CITIZEN-SERVICE
        predicates:
        - Path=/citizen/**
        filters:
          - AuthenticationFilter

      - id: SECURITY-SERVICE
        uri:
          lb://SECURITY-SERVICE
        predicates:
          - Path=/auth/**
        
      - id: VACCINATION-CENTER-SERVICE
        uri:
          lb://VACCINATION-CENTER-SERVICE
        predicates:
        - Path=/vaccinationcenter/**
        
        
